# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('postcode', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('profile_researched', models.TextField(blank=True, max_length=400)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Enterprise')),
            ],
        ),
    ]
