# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20171128_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='offer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.Offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='enterprise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.Enterprise'),
        ),
    ]
